import { expect, test } from '@playwright/test'
import { DEFAULT_DESCRIPTION, DEPENDENCY_PAYLOAD } from '../src/features/vulnerabilities/dependencies/fixtures'

for (const width of [1440, 390]) {
  test(`demonstrates a dependency update at ${width}px`, async ({ page }) => {
    await page.setViewportSize({ width, height: 900 })
    await page.emulateMedia({ reducedMotion: 'reduce' })
    const errors: string[] = []
    const dialogs: string[] = []
    page.on('pageerror', (error) => errors.push(error.message))
    page.on('dialog', async (dialog) => {
      dialogs.push(dialog.message())
      await dialog.dismiss()
    })
    await page.goto('/talk/dependencies/0')
    await expect(page.getByRole('heading', { name: 'Уязвимые npm-зависимости', exact: true })).toBeVisible()
    await page.getByRole('button', { name: 'Следующий слайд', exact: true }).click()
    await expect(page.getByRole('heading', { name: 'Зависимости: найти и исправить' })).toBeVisible()
    expect(await page.evaluate(() => document.documentElement.scrollWidth)).toBe(width)
    await page.screenshot({ path: `test-results/dependencies-audit-${width}.png`, fullPage: true })
    await page.getByRole('button', { name: 'Следующий слайд', exact: true }).click()
    await expect(page.getByRole('tabpanel')).toContainText('dangerouslySetInnerHTML')
    await page.getByRole('tab', { name: 'Исправлено', exact: true }).click()
    await expect(page.getByRole('tabpanel')).toContainText('FixedProductDescription')
    await expect(page.getByRole('tabpanel')).not.toContainText('dangerouslySetInnerHTML')
    await page.getByRole('button', { name: 'Следующий слайд', exact: true }).click()
    await expect(page).toHaveURL(/\/talk\/dependencies\/3$/)
    await page.getByRole('button', { name: 'Открыть демонстрацию' }).click()
    await expect(page).toHaveURL(/\/site\/product$/)
    const preview = page.getByTestId('product-preview')
    await expect(preview).toHaveText(DEFAULT_DESCRIPTION)
    await expect(page.getByTestId('dependency-version')).toHaveText('demo-description@1.0.0')
    await page.getByRole('button', { name: 'Подставить payload' }).click()
    await expect(page.getByLabel('Описание товара', { exact: true })).toHaveValue(DEPENDENCY_PAYLOAD)
    await page.getByRole('button', { name: 'Применить описание' }).click()
    await expect.poll(() => dialogs).toEqual(['Код из зависимости выполнен'])
    await expect(preview.locator('img')).toHaveCount(1)
    await page.getByText('Исправлено', { exact: true }).click()
    await expect(page.getByTestId('dependency-version')).toHaveText('demo-description@1.0.1')
    await expect(preview).toHaveText(DEPENDENCY_PAYLOAD)
    await expect(preview.locator('img')).toHaveCount(0)
    await page.getByRole('button', { name: 'Применить описание' }).click()
    await expect(preview).toHaveText(DEPENDENCY_PAYLOAD)
    expect(await page.evaluate(() => document.documentElement.scrollWidth)).toBe(width)
    const productImage = page.getByRole('img', { name: 'Каталог электротехнической продукции' })
    await expect.poll(() => productImage.evaluate((img: HTMLImageElement) => img.naturalWidth)).toBeGreaterThan(0)
    await page.screenshot({ path: `test-results/dependencies-fixed-${width}.png`, fullPage: true })
    expect(dialogs).toHaveLength(1)
    await page.getByText('Уязвимо', { exact: true }).click()
    await expect.poll(() => dialogs.length).toBe(2)
    await page.getByRole('button', { name: 'Сбросить', exact: true }).click()
    await expect(preview).toHaveText(DEFAULT_DESCRIPTION)
    await expect(page.getByLabel('Описание товара', { exact: true })).toHaveValue(DEFAULT_DESCRIPTION)
    await page.keyboard.press('Escape')
    await expect(page).toHaveURL(/\/talk\/dependencies\/3$/)
    await page.goto('/site/delivery')
    await page.getByRole('button', { name: 'К слайду' }).click()
    await expect(page).toHaveURL(/\/talk\/csrf\/3$/)
    await page.goto('/site/product')
    await page.getByRole('button', { name: 'К слайду' }).click()
    await expect(page).toHaveURL(/\/talk\/dependencies\/3$/)
    expect(errors).toEqual([])
  })
}
