import { expect, test } from '@playwright/test'

for (const width of [1440, 390]) {
  test(`isolates real prototype pollution and rejects it with a schema at ${width}px`, async ({ page, context }) => {
    test.setTimeout(60_000)
    await page.setViewportSize({ width, height: 900 })
    await page.emulateMedia({ reducedMotion: 'reduce' })
    const errors: string[] = []
    page.on('pageerror', (error) => errors.push(error.message))
    page.on('console', (message) => {
      if (message.type() === 'error' && !message.location().url.endsWith('/favicon.ico')) errors.push(message.text())
    })
    await page.goto('/talk/prototype-pollution/0')
    await expect(page.getByRole('heading', { name: 'Prototype Pollution', exact: true })).toBeVisible()
    expect(await page.evaluate(() => document.documentElement.scrollWidth)).toBe(width)
    await page.screenshot({ path: `test-results/prototype-overview-${width}.png`, fullPage: true, animations: 'disabled' })
    await page.getByRole('button', { name: 'Следующий слайд', exact: true }).click()
    await expect(page.getByRole('heading', { name: 'Prototype Pollution: фронтенд-код' })).toBeVisible()
    await expect(page.getByRole('tabpanel')).toContainText('target[key] ??= {}')
    await page.getByRole('tab', { name: 'Исправлено', exact: true }).click()
    await expect(page.getByRole('tabpanel')).toContainText('settingsSchema.parse(input)')
    await expect(page.getByRole('tabpanel')).toContainText('.strict()')
    await page.screenshot({ path: `test-results/prototype-code-${width}.png`, fullPage: true, animations: 'disabled' })
    await page.getByRole('button', { name: 'Следующий слайд', exact: true }).click()
    await page.getByRole('button', { name: 'Открыть демонстрацию' }).click()
    await expect(page).toHaveURL(/\/site\/catalog$/)
    await expect(page.getByTestId('prototype-fee')).toHaveText('undefined')
    await expect(page.getByTestId('delivery-estimate')).toHaveText('490 ₽')
    await expect(page.getByRole('button', { name: 'Скопировать payload' })).toHaveCount(0)
    await expect.poll(() => page.getByRole('img', { name: 'Каталог электротехнической продукции' }).evaluate((img: HTMLImageElement) => img.naturalWidth)).toBeGreaterThan(0)
    expect(await page.evaluate(() => document.documentElement.scrollWidth)).toBe(width)

    for (const variant of ['__proto__', 'constructor.prototype']) {
      await page.getByRole('combobox', { name: 'Входные данные' }).click()
      await page.getByText(`Payload: ${variant}`, { exact: true }).click()
      const payload = await page.getByLabel('JSON настроек').inputValue()
      await page.getByRole('button', { name: 'Импортировать настройки' }).click()
      await expect(page.getByTestId('after-parse')).toHaveText('undefined')
      await expect(page.getByTestId('prototype-fee')).toHaveText('0')
      await expect(page.getByTestId('new-object-fee')).toHaveText('0')
      await expect(page.getByTestId('has-own-fee')).toHaveText('false')
      await expect(page.getByTestId('delivery-estimate')).toHaveText('0 ₽')
      // The visible React application keeps its own clean prototype realm.
      expect(await page.evaluate(() => Object.hasOwn(Object.prototype, 'deliveryFee'))).toBe(false)
      await page.screenshot({ path: `test-results/prototype-vulnerable-${variant}-${width}.png`, fullPage: true, animations: 'disabled' })
      await page.getByText('Исправлено', { exact: true }).click()
      await expect.poll(async () => (await context.cookies()).find((cookie) => cookie.name === 'demo-mode')?.value).toBe('fixed')
      await expect(page.getByText('Импорт отклонён:', { exact: false })).toBeVisible()
      await expect(page.getByLabel('JSON настроек')).toHaveValue(payload)
      await expect(page.getByTestId('prototype-fee')).toHaveText('undefined')
      await expect(page.getByTestId('new-object-fee')).toHaveText('undefined')
      await expect(page.getByTestId('has-own-fee')).toHaveText('false')
      await expect(page.getByTestId('delivery-estimate')).toHaveText('490 ₽')
      await page.screenshot({ path: `test-results/prototype-fixed-${variant}-${width}.png`, fullPage: true, animations: 'disabled' })
      await page.getByText('Уязвимо', { exact: true }).click()
      await expect(page.getByTestId('prototype-fee')).toHaveText('0')
      await page.getByRole('button', { name: 'Сбросить', exact: true }).click()
      await expect(page.getByTestId('prototype-fee')).toHaveText('undefined')
      await expect(page.getByTestId('delivery-estimate')).toHaveText('490 ₽')
    }

    for (const mode of ['Уязвимо', 'Исправлено']) {
      await page.getByText(mode, { exact: true }).click()
      await expect(page.getByTestId('prototype-demo')).toHaveAttribute('data-mode', mode === 'Исправлено' ? 'fixed' : 'vulnerable')
      await expect(page.getByTestId('prototype-demo')).toHaveAttribute('aria-busy', 'false')
      await expect(page.getByLabel('JSON настроек')).toBeEnabled()
      await page.getByLabel('JSON настроек').fill('{"view":{"sort":"name","pageSize":36}}')
      await page.getByRole('button', { name: 'Импортировать настройки' }).click()
      await expect(page.getByTestId('catalog-view')).toContainText('По названию')
      await expect(page.getByTestId('catalog-view')).toContainText('36')
      await expect(page.getByTestId('delivery-estimate')).toHaveText('490 ₽')
      await page.getByLabel('JSON настроек').fill('{bad json')
      await page.getByRole('button', { name: 'Импортировать настройки' }).click()
      await expect(page.getByText('Некорректный JSON.', { exact: true })).toBeVisible()
      for (const input of ['null', '[]']) {
        await page.getByLabel('JSON настроек').fill(input)
        await page.getByRole('button', { name: 'Импортировать настройки' }).click()
        await expect(page.getByText('Ожидается JSON-объект настроек.', { exact: true })).toBeVisible()
      }
      await page.getByLabel('JSON настроек').fill('{"nested":'.repeat(22) + '{}' + '}'.repeat(22))
      await page.getByRole('button', { name: 'Импортировать настройки' }).click()
      await expect(page.getByText('Слишком много уровней вложенности: максимум 20.', { exact: true })).toBeVisible()
      await page.getByRole('button', { name: 'Сбросить', exact: true }).click()
      await expect(page.getByTestId('catalog-view')).toContainText('По цене')
    }
    expect(await page.evaluate(() => Object.hasOwn(Object.prototype, 'deliveryFee'))).toBe(false)
    expect(await page.evaluate(() => document.documentElement.scrollWidth)).toBe(width)
    await page.keyboard.press('Escape')
    await expect(page).toHaveURL(/\/talk\/prototype-pollution\/2$/)
    expect(errors).toEqual([])
  })
}
