import { expect, test } from '@playwright/test'

test('opens the demo from the deck and returns to the same slide', async ({ page }) => {
  await page.goto('/talk')
  await expect(page).toHaveURL(/\/talk\/intro\/0$/)
  await page.keyboard.press('ArrowRight')
  await expect(page).toHaveURL(/\/talk\/intro\/1$/)
  await page.getByRole('link', { name: /XSS/ }).click()
  await expect(page).toHaveURL(/\/talk\/xss\/0$/)
  await page.keyboard.press('ArrowRight')
  await expect(page).toHaveURL(/\/talk\/xss\/1$/)
  await expect(page.getByRole('heading', { name: 'XSS: уязвимый код и исправление', exact: true })).toBeVisible()
  await page.keyboard.press('ArrowRight')
  await expect(page).toHaveURL(/\/talk\/xss\/2$/)
  await page.getByRole('button', { name: 'Открыть демонстрацию' }).click()
  await expect(page).toHaveURL(/\/site\/comments$/)
  await expect(page.getByTestId('comment-input')).toBeVisible()
  await page.keyboard.press('Escape')
  await expect(page).toHaveURL(/\/talk\/xss\/2$/)
})

test('executes stored XSS only in vulnerable mode and resets comments', async ({ page }) => {
  await page.request.post('/api/site/reset')
  await page.request.post('/api/demo-mode', { data: { mode: 'vulnerable' } })
  try {
    await page.goto('/site/comments')
    await expect(page.getByTestId('comment')).toHaveCount(2)
    const payload = '<img src=x onerror="document.documentElement.dataset.xss = document.cookie">'
    await page.getByTestId('comment-input').fill(payload)
    await page.getByTestId('comment-submit').click()
    await expect(page.locator('html')).toHaveAttribute('data-xss', /session=sess_alex_7f3a9c/)

    await page.reload()
    await expect(page.locator('html')).toHaveAttribute('data-xss', /session=sess_alex_7f3a9c/)
    await page.getByText('Исправлено', { exact: true }).click()
    await expect(page.getByTestId('comment').last()).toContainText(payload)

    const response = await page.reload()
    expect(response?.headers()['x-frame-options']).toBe('DENY')
    await expect(page.getByTestId('comments-list').locator('img')).toHaveCount(0)
    await expect(page.locator('html')).not.toHaveAttribute('data-xss')
    expect(await page.evaluate(() => document.cookie)).not.toContain('session=')
    expect((await page.context().cookies()).find((cookie) => cookie.name === 'session')?.httpOnly).toBe(true)

    await page.getByRole('button', { name: 'Сбросить' }).click()
    await expect(page.getByTestId('comment')).toHaveCount(2)
    await expect(page.getByTestId('comments-list')).not.toContainText(payload)
  } finally {
    await page.request.post('/api/site/reset')
  }
})

test('shows backend topics, notes and the real XSS fix on mobile', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 })
  await page.goto('/talk/xss/2')
  await page.getByRole('button', { name: 'Содержание', exact: true }).focus()
  await page.keyboard.press('Enter')
  await expect(page.getByRole('dialog')).toBeVisible()
  await page.keyboard.press('ArrowRight')
  await expect(page).toHaveURL(/\/talk\/xss\/2$/)
  await page.getByRole('navigation', { name: 'Темы доклада' }).getByRole('link', { name: 'SQL Injection' }).click()
  await expect(page.getByRole('heading', { name: 'SQL Injection', exact: true })).toBeVisible()
  await expect(page.getByRole('button', { name: 'Открыть демонстрацию' })).toHaveCount(0)
  await page.getByRole('button', { name: 'Заметки докладчика', exact: true }).click()
  await expect(page.getByRole('dialog')).toContainText('Cybersecurity.pptx, слайд 14')
  await page.keyboard.press('Escape')
  await page.goto('/talk/xss/1')
  await page.getByRole('tab', { name: 'Исправлено', exact: true }).click()
  await expect(page.getByRole('tabpanel')).toContainText('CommentBodyFixed')
  expect(await page.evaluate(() => document.documentElement.scrollWidth)).toBe(390)
  await page.getByRole('button', { name: 'Следующий слайд', exact: true }).click()
  await expect(page).toHaveURL(/\/talk\/xss\/2$/)
  await page.getByRole('button', { name: 'Следующий слайд', exact: true }).click()
  await expect(page).toHaveURL(/\/talk\/xss\/3$/)
  await page.getByRole('button', { name: 'Открыть демонстрацию' }).click()
  await expect(page).toHaveURL(/\/site\/comments$/)
  await expect(page.getByRole('radio', { name: 'Исправлено', exact: true })).toBeChecked()
})
