import { expect, test } from '@playwright/test'
import demoData from '../src/features/vulnerabilities/third-party-scripts/demo-data.json' with { type: 'json' }

for (const width of [1440, 390]) {
  test(`blocks a modified third-party script using real SRI at ${width}px`, async ({ page }) => {
    await page.setViewportSize({ width, height: 900 })
    await page.emulateMedia({ reducedMotion: 'reduce' })
    const errors: string[] = []
    const integrityErrors: string[] = []
    const leaks: string[] = []
    page.on('pageerror', (error) => errors.push(error.message))
    page.on('console', (message) => {
      if (message.type() !== 'error' || message.location().url.endsWith('/favicon.ico')) return
      if (/integrity|valid digest/i.test(message.text())) integrityErrors.push(message.text())
      else errors.push(message.text())
    })
    page.on('request', (request) => {
      if (request.url().endsWith('/third-party/collect')) leaks.push(request.postData() ?? '')
    })
    await page.goto('/talk/third-party-scripts/0')
    await expect(page.getByRole('heading', { name: 'Сторонние скрипты (Magecart)' })).toBeVisible()
    await page.getByRole('button', { name: 'Следующий слайд', exact: true }).click()
    await expect(page.getByRole('heading', { name: 'Что проверяет SRI' })).toBeVisible()
    expect(await page.evaluate(() => document.documentElement.scrollWidth)).toBe(width)
    await page.getByRole('button', { name: 'Следующий слайд', exact: true }).click()
    const ourCode = page.getByRole('tabpanel').locator('.backend-code')
    const vendorCode = page.getByRole('region', { name: 'Подменённая аналитика: чтение и отправка полей формы' })
    await expect(ourCode).toContainText('createAnalyticsScript')
    await expect(ourCode).not.toContainText('script.integrity')
    await expect(vendorCode).toContainText("form.elements.namedItem('email').value")
    const unchangedVendor = await vendorCode.textContent()
    await page.getByRole('tab', { name: 'Исправлено', exact: true }).click()
    await expect(ourCode).toContainText('script.integrity = TRUSTED_ANALYTICS_INTEGRITY')
    await expect(vendorCode).toHaveText(unchangedVendor!)
    await page.screenshot({ path: `test-results/third-party-code-${width}.png`, fullPage: true, animations: 'disabled' })
    await page.getByRole('button', { name: 'Следующий слайд', exact: true }).click()
    await page.getByRole('button', { name: 'Открыть демонстрацию' }).click()
    await expect(page).toHaveURL(/\/site\/checkout$/)
    await expect(page.getByRole('button', { name: 'Скопировать payload' })).toHaveCount(0)
    const submit = page.getByRole('button', { name: 'Оформить заказ' })
    await expect(page.getByLabel('Email покупателя')).toHaveValue(demoData.email)
    await expect(page.getByLabel('Email покупателя')).toHaveAttribute('readonly', '')
    const capturedRequest = page.waitForResponse((response) => response.url().endsWith('/third-party/collect'))
    await submit.click()
    const capturedResponse = await capturedRequest
    expect(capturedResponse.status()).toBe(204)
    expect(capturedResponse.request().postDataJSON().data).toEqual(demoData)
    expect(new URL(capturedResponse.url()).origin).not.toBe(new URL(page.url()).origin)
    expect((await capturedResponse.request().allHeaders()).cookie).toBeUndefined()
    await expect(page.getByTestId('captured-data')).toContainText(demoData.email)
    await expect(page.getByTestId('analytics-event')).toHaveText('order_submitted')
    await expect(submit).toBeEnabled()
    await expect.poll(() => page.getByRole('img', { name: 'Каталог электротехнической продукции' }).evaluate((img: HTMLImageElement) => img.naturalWidth)).toBeGreaterThan(0)
    expect(await page.evaluate(() => document.documentElement.scrollWidth)).toBe(width)
    await page.screenshot({ path: `test-results/third-party-vulnerable-${width}.png`, fullPage: true, animations: 'disabled' })

    await page.getByText('Исправлено', { exact: true }).click()
    await expect(page.getByTestId('script-status')).toHaveText('Ещё не загружен')
    await expect(page.getByText('Включена', { exact: true })).toBeVisible()
    await submit.click()
    await expect(page.getByTestId('script-status')).toHaveText('Браузер отклонил загрузку')
    await expect(page.getByTestId('capture-empty')).toHaveText('Данных этого запуска нет')
    await expect(page.getByTestId('analytics-event')).toHaveText('Нет события')
    await expect.poll(() => integrityErrors.length).toBeGreaterThan(0)
    expect(leaks).toHaveLength(1)
    await page.screenshot({ path: `test-results/third-party-fixed-${width}.png`, fullPage: true, animations: 'disabled' })

    // Перезагрузка применяет CSP нового fixed-документа; исходный файл должен пройти.
    const response = await page.reload()
    expect(response?.headers()['content-security-policy']).toContain(`http://127.0.0.1:${process.env.CSRF_ATTACKER_PORT ?? 3001}`)
    await page.getByText('Исходный', { exact: true }).click()
    await expect(page.getByRole('radio', { name: 'Исходный', exact: true })).toBeChecked()
    await submit.click()
    await expect(page.getByTestId('script-status')).toHaveText('Выполнен')
    await expect(page.getByTestId('analytics-event')).toHaveText('order_submitted')
    await expect(page.getByTestId('capture-empty')).toHaveText('Данных этого запуска нет')
    expect(leaks).toHaveLength(1)
    await page.getByRole('button', { name: 'Сбросить', exact: true }).click()
    await expect(page.getByTestId('analytics-event')).toHaveText('Нет события')
    await expect(page.getByTestId('script-status')).toHaveText('Ещё не загружен')
    await page.keyboard.press('Escape')
    await expect(page).toHaveURL(/\/talk\/third-party-scripts\/3$/)
    await page.goto('/site/delivery')
    await page.getByRole('button', { name: 'К слайду' }).click()
    await expect(page).toHaveURL(/\/talk\/csrf\/3$/)
    if (width === 1440) {
      await page.goto('/site/product')
      const navigation = page.waitForResponse((item) => item.request().isNavigationRequest() && item.url().endsWith('/site/checkout'))
      await page.getByRole('link', { name: 'Заказ', exact: true }).click()
      expect((await navigation).headers()['content-security-policy']).toContain('http://127.0.0.1:')
      await page.getByText('Исходный', { exact: true }).click()
      await submit.click()
      await expect(page.getByTestId('script-status')).toHaveText('Выполнен')
      await expect(page.getByTestId('capture-empty')).toHaveText('Данных этого запуска нет')
      const homeNavigation = page.waitForResponse((item) => item.request().isNavigationRequest() && item.url().endsWith('/site'))
      await page.getByRole('link', { name: 'Главная', exact: true }).first().click()
      expect((await homeNavigation).headers()['content-security-policy']).not.toContain('http://127.0.0.1:')
    }
    expect(errors).toEqual([])
  })
}
